<?php 
	
return array
(
	"ABW" => array(
	"iso" => "AW",
	"name" => "ARUBA",
	"country" => "Aruba",
	"numcode" => "533",
	"flag" => "Aruba-Flag.png",
	),
	"AFG" => array(
	"iso" => "AF",
	"name" => "AFGHANISTAN",
	"country" => "Afghanistan",
	"numcode" => "4",
	"flag" => "Afghanistan-Flag.png",
	),
	"AGO" => array(
	"iso" => "AO",
	"name" => "ANGOLA",
	"country" => "Angola",
	"numcode" => "24",
	"flag" => "Angola-Flag.png",
	),
	"AIA" => array(
	"iso" => "AI",
	"name" => "ANGUILLA",
	"country" => "Anguilla",
	"numcode" => "660",
	"flag" => "Anguilla-Flag.png",
	),
	"ALB" => array(
	"iso" => "AL",
	"name" => "ALBANIA",
	"country" => "Albania",
	"numcode" => "8",
	"flag" => "Albania-Flag.png",
	),
	"AND" => array(
	"iso" => "AD",
	"name" => "ANDORRA",
	"country" => "Andorra",
	"numcode" => "20",
	"flag" => "Andorra-Flag.png",
	),
	"ANT" => array(
	"iso" => "AN",
	"name" => "NETHERLANDS ANTILLES",
	"country" => "Netherlands Antilles",
	"numcode" => "530",
	"flag" => "Netherlands-Antilles-Flag.png",
	),
	"AQ" => array(
	"iso" => "AQ",
	"name" => "ANTARCTICA",
	"country" => "Antarctica",
	"numcode" => "0",
	"flag" => "Antarctica-Flag.png",
	),
	"ARE" => array(
	"iso" => "AE",
	"name" => "UNITED ARAB EMIRATES",
	"country" => "United Arab Emirates",
	"numcode" => "784",
	"flag" => "United-Arab-Emirates-Flag.png",
	),
	"ARG" => array(
	"iso" => "AR",
	"name" => "ARGENTINA",
	"country" => "Argentina",
	"numcode" => "32",
	"flag" => "Argentina-Flag.png",
	),
	"ARM" => array(
	"iso" => "AM",
	"name" => "ARMENIA",
	"country" => "Armenia",
	"numcode" => "51",
	"flag" => "Armenia-Flag.png",
	),
	"ASM" => array(
	"iso" => "AS",
	"name" => "AMERICAN SAMOA",
	"country" => "American Samoa",
	"numcode" => "16",
	"flag" => "American-Samoa-Flag.png",
	),
	"ATG" => array(
	"iso" => "AG",
	"name" => "ANTIGUA AND BARBUDA",
	"country" => "Antigua and Barbuda",
	"numcode" => "28",
	"flag" => "Antigua-and-Barbuda-Flag.png",
	),
	"AUS" => array(
	"iso" => "AU",
	"name" => "AUSTRALIA",
	"country" => "Australia",
	"numcode" => "36",
	"flag" => "Australia-Flag.png",
	),
	"AUT" => array(
	"iso" => "AT",
	"name" => "AUSTRIA",
	"country" => "Austria",
	"numcode" => "40",
	"flag" => "Austria-Flag.png",
	),
	"AZE" => array(
	"iso" => "AZ",
	"name" => "AZERBAIJAN",
	"country" => "Azerbaijan",
	"numcode" => "31",
	"flag" => "Azerbaijan-Flag.png",
	),
	"BDI" => array(
	"iso" => "BI",
	"name" => "BURUNDI",
	"country" => "Burundi",
	"numcode" => "108",
	"flag" => "Burundi-Flag.png",
	),
	"BEL" => array(
	"iso" => "BE",
	"name" => "BELGIUM",
	"country" => "Belgium",
	"numcode" => "56",
	"flag" => "Belgium-Flag.png",
	),
	"BEN" => array(
	"iso" => "BJ",
	"name" => "BENIN",
	"country" => "Benin",
	"numcode" => "204",
	"flag" => "Benin-Flag.png",
	),
	"BFA" => array(
	"iso" => "BF",
	"name" => "BURKINA FASO",
	"country" => "Burkina Faso",
	"numcode" => "854",
	"flag" => "Burkina-Faso-Flag.png",
	),
	"BGD" => array(
	"iso" => "BD",
	"name" => "BANGLADESH",
	"country" => "Bangladesh",
	"numcode" => "50",
	"flag" => "Bangladesh-Flag.png",
	),
	"BGR" => array(
	"iso" => "BG",
	"name" => "BULGARIA",
	"country" => "Bulgaria",
	"numcode" => "100",
	"flag" => "Bulgaria-Flag.png",
	),
	"BHR" => array(
	"iso" => "BH",
	"name" => "BAHRAIN",
	"country" => "Bahrain",
	"numcode" => "48",
	"flag" => "Bahrain-Flag.png",
	),
	"BHS" => array(
	"iso" => "BS",
	"name" => "BAHAMAS",
	"country" => "Bahamas",
	"numcode" => "44",
	"flag" => "Bahamas-Flag.png",
	),
	"BIH" => array(
	"iso" => "BA",
	"name" => "BOSNIA AND HERZEGOVINA",
	"country" => "Bosnia and Herzegovina",
	"numcode" => "70",
	"flag" => "Bosnia-and-Herzegovina-Flag.png",
	),
	"BLR" => array(
	"iso" => "BY",
	"name" => "BELARUS",
	"country" => "Belarus",
	"numcode" => "112",
	"flag" => "Belarus-Flag.png",
	),
	"BLZ" => array(
	"iso" => "BZ",
	"name" => "BELIZE",
	"country" => "Belize",
	"numcode" => "84",
	"flag" => "Belize-Flag.png",
	),
	"BMU" => array(
	"iso" => "BM",
	"name" => "BERMUDA",
	"country" => "Bermuda",
	"numcode" => "60",
	"flag" => "Bermuda-Flag.png",
	),
	"BOL" => array(
	"iso" => "BO",
	"name" => "BOLIVIA",
	"country" => "Bolivia",
	"numcode" => "68",
	"flag" => "Bolivia-Flag.png",
	),
	"BRA" => array(
	"iso" => "BR",
	"name" => "BRAZIL",
	"country" => "Brazil",
	"numcode" => "76",
	"flag" => "Brazil-Flag.png",
	),
	"BRB" => array(
	"iso" => "BB",
	"name" => "BARBADOS",
	"country" => "Barbados",
	"numcode" => "52",
	"flag" => "Barbados-Flag.png",
	),
	"BRN" => array(
	"iso" => "BN",
	"name" => "BRUNEI DARUSSALAM",
	"country" => "Brunei Darussalam",
	"numcode" => "96",
	"flag" => "Brunei-Flag.png",
	),
	"BTN" => array(
	"iso" => "BT",
	"name" => "BHUTAN",
	"country" => "Bhutan",
	"numcode" => "64",
	"flag" => "Bhutan-Flag.png",
	),
	"BWA" => array(
	"iso" => "BW",
	"name" => "BOTSWANA",
	"country" => "Botswana",
	"numcode" => "72",
	"flag" => "Botswana-Flag.png",
	),
	"CAF" => array(
	"iso" => "CF",
	"name" => "CENTRAL AFRICAN REPUBLIC",
	"country" => "Central African Republic",
	"numcode" => "140",
	"flag" => "Central-African-Republic-Flag.png",
	),
	"CAN" => array(
	"iso" => "CA",
	"name" => "CANADA",
	"country" => "Canada",
	"numcode" => "124",
	"flag" => "Canada-Flag.png",
	),
	"CHE" => array(
	"iso" => "CH",
	"name" => "SWITZERLAND",
	"country" => "Switzerland",
	"numcode" => "756",
	"flag" => "Switzerland-Flag.png",
	),
	"CHL" => array(
	"iso" => "CL",
	"name" => "CHILE",
	"country" => "Chile",
	"numcode" => "152",
	"flag" => "Chile-Flag.png",
	),
	"CHN" => array(
	"iso" => "CN",
	"name" => "CHINA",
	"country" => "China",
	"numcode" => "156",
	"flag" => "China-Flag.png",
	),
	"CIV" => array(
	"iso" => "CI",
	"name" => "COTE D'IVOIRE",
	"country" => "Cote D'Ivoire",
	"numcode" => "384",
	"flag" => "Cote-DIvoire-Flag.png",
	),
	"CMR" => array(
	"iso" => "CM",
	"name" => "CAMEROON",
	"country" => "Cameroon",
	"numcode" => "120",
	"flag" => "Cameroon-Flag.png",
	),
	"COD" => array(
	"iso" => "CD",
	"name" => "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
	"country" => "Congo, the Democratic Republic of the",
	"numcode" => "180",
	"flag" => "Congo-Kinshasa-Flag.png",
	),
	"COG" => array(
	"iso" => "CG",
	"name" => "CONGO",
	"country" => "Congo",
	"numcode" => "178",
	"flag" => "Congo-Brazzaville-Flag.png",
	),
	"COK" => array(
	"iso" => "CK",
	"name" => "COOK ISLANDS",
	"country" => "Cook Islands",
	"numcode" => "184",
	"flag" => "Cook-Islands-Flag.png",
	),
	"COL" => array(
	"iso" => "CO",
	"name" => "COLOMBIA",
	"country" => "Colombia",
	"numcode" => "170",
	"flag" => "Colombia-Flag.png",
	),
	"COM" => array(
	"iso" => "KM",
	"name" => "COMOROS",
	"country" => "Comoros",
	"numcode" => "174",
	"flag" => "Comoros-Flag.png",
	),
	"CPV" => array(
	"iso" => "CV",
	"name" => "CAPE VERDE",
	"country" => "Cape Verde",
	"numcode" => "132",
	"flag" => "Cape-Verde-Flag.png",
	),
	"CRI" => array(
	"iso" => "CR",
	"name" => "COSTA RICA",
	"country" => "Costa Rica",
	"numcode" => "188",
	"flag" => "Costa-Rica-Flag.png",
	),
	"CS" => array(
	"iso" => "CS",
	"name" => "SERBIA AND MONTENEGRO",
	"country" => "Serbia and Montenegro",
	"numcode" => "0",
	"flag" => "Serbia-Flag.png",
	),
	"CUB" => array(
	"iso" => "CU",
	"name" => "CUBA",
	"country" => "Cuba",
	"numcode" => "192",
	"flag" => "Cuba-Flag.png",
	),
	"CYM" => array(
	"iso" => "KY",
	"name" => "CAYMAN ISLANDS",
	"country" => "Cayman Islands",
	"numcode" => "136",
	"flag" => "Cayman-Islands-Flag.png",
	),
	"CYP" => array(
	"iso" => "CY",
	"name" => "CYPRUS",
	"country" => "Cyprus",
	"numcode" => "196",
	"flag" => "Cyprus-Flag.png",
	),
	"CZE" => array(
	"iso" => "CZ",
	"name" => "CZECH REPUBLIC",
	"country" => "Czech Republic",
	"numcode" => "203",
	"flag" => "Czech-Republic-Flag.png",
	),
	"DEU" => array(
	"iso" => "DE",
	"name" => "GERMANY",
	"country" => "Germany",
	"numcode" => "276",
	"flag" => "Germany-Flag.png",
	),
	"DJI" => array(
	"iso" => "DJ",
	"name" => "DJIBOUTI",
	"country" => "Djibouti",
	"numcode" => "262",
	"flag" => "Djibouti-Flag.png",
	),
	"DMA" => array(
	"iso" => "DM",
	"name" => "DOMINICA",
	"country" => "Dominica",
	"numcode" => "212",
	"flag" => "Dominica-Flag.png",
	),
	"DNK" => array(
	"iso" => "DK",
	"name" => "DENMARK",
	"country" => "Denmark",
	"numcode" => "208",
	"flag" => "Denmark-Flag.png",
	),
	"DOM" => array(
	"iso" => "DO",
	"name" => "DOMINICAN REPUBLIC",
	"country" => "Dominican Republic",
	"numcode" => "214",
	"flag" => "Dominican-Republic-Flag.png",
	),
	"DZA" => array(
	"iso" => "DZ",
	"name" => "ALGERIA",
	"country" => "Algeria",
	"numcode" => "12",
	"flag" => "Algeria-Flag.png",
	),
	"ECU" => array(
	"iso" => "EC",
	"name" => "ECUADOR",
	"country" => "Ecuador",
	"numcode" => "218",
	"flag" => "Ecuador-Flag.png",
	),
	"EGY" => array(
	"iso" => "EG",
	"name" => "EGYPT",
	"country" => "Egypt",
	"numcode" => "818",
	"flag" => "Egypt-Flag.png",
	),
	"ERI" => array(
	"iso" => "ER",
	"name" => "ERITREA",
	"country" => "Eritrea",
	"numcode" => "232",
	"flag" => "Eritrea-Flag.png",
	),
	"ESH" => array(
	"iso" => "EH",
	"name" => "WESTERN SAHARA",
	"country" => "Western Sahara",
	"numcode" => "732",
	"flag" => "Western-Sahara-Flag.png",
	),
	"ESP" => array(
	"iso" => "ES",
	"name" => "SPAIN",
	"country" => "Spain",
	"numcode" => "724",
	"flag" => "Spain-Flag.png",
	),
	"EST" => array(
	"iso" => "EE",
	"name" => "ESTONIA",
	"country" => "Estonia",
	"numcode" => "233",
	"flag" => "Estonia-Flag.png",
	),
	"ETH" => array(
	"iso" => "ET",
	"name" => "ETHIOPIA",
	"country" => "Ethiopia",
	"numcode" => "231",
	"flag" => "Ethiopia-Flag.png",
	),
	"FIN" => array(
	"iso" => "FI",
	"name" => "FINLAND",
	"country" => "Finland",
	"numcode" => "246",
	"flag" => "Finland-Flag.png",
	),
	"FJI" => array(
	"iso" => "FJ",
	"name" => "FIJI",
	"country" => "Fiji",
	"numcode" => "242",
	"flag" => "Fiji-Flag.png",
	),
	"FLK" => array(
	"iso" => "FK",
	"name" => "FALKLAND ISLANDS (MALVINAS)",
	"country" => "Falkland Islands (Malvinas)",
	"numcode" => "238",
	"flag" => "United-Kingdom-Flag.png",
	),
	"FRA" => array(
	"iso" => "FR",
	"name" => "FRANCE",
	"country" => "France",
	"numcode" => "250",
	"flag" => "France-Flag.png",
	),
	"FRO" => array(
	"iso" => "FO",
	"name" => "FAROE ISLANDS",
	"country" => "Faroe Islands",
	"numcode" => "234",
	"flag" => "Faroes-Flag.png",
	),
	"FSM" => array(
	"iso" => "FM",
	"name" => "MICRONESIA, FEDERATED STATES OF",
	"country" => "Micronesia, Federated States of",
	"numcode" => "583",
	"flag" => "Micronesia-Flag.png",
	),
	"GAB" => array(
	"iso" => "GA",
	"name" => "GABON",
	"country" => "Gabon",
	"numcode" => "266",
	"flag" => "Gabon-Flag.png",
	),
	"GBR" => array(
	"iso" => "GB",
	"name" => "UNITED KINGDOM",
	"country" => "United Kingdom",
	"numcode" => "826",
	"flag" => "United-Kingdom-Flag.png",
	),
	"GEO" => array(
	"iso" => "GE",
	"name" => "GEORGIA",
	"country" => "Georgia",
	"numcode" => "268",
	"flag" => "Georgia-Flag.png",
	),
	"GHA" => array(
	"iso" => "GH",
	"name" => "GHANA",
	"country" => "Ghana",
	"numcode" => "288",
	"flag" => "Ghana-Flag.png",
	),
	"GIB" => array(
	"iso" => "GI",
	"name" => "GIBRALTAR",
	"country" => "Gibraltar",
	"numcode" => "292",
	"flag" => "Gibraltar-Flag.png",
	),
	"GIN" => array(
	"iso" => "GN",
	"name" => "GUINEA",
	"country" => "Guinea",
	"numcode" => "324",
	"flag" => "Guinea-Flag.png",
	),
	"GLP" => array(
	"iso" => "GP",
	"name" => "GUADELOUPE",
	"country" => "Guadeloupe",
	"numcode" => "312",
	"flag" => "France-Flag.png",
	),
	"GMB" => array(
	"iso" => "GM",
	"name" => "GAMBIA",
	"country" => "Gambia",
	"numcode" => "270",
	"flag" => "Gambia-Flag.png",
	),
	"GNB" => array(
	"iso" => "GW",
	"name" => "GUINEA-BISSAU",
	"country" => "Guinea-Bissau",
	"numcode" => "624",
	"flag" => "Guinea-Bissau-Flag.png",
	),
	"GNQ" => array(
	"iso" => "GQ",
	"name" => "EQUATORIAL GUINEA",
	"country" => "Equatorial Guinea",
	"numcode" => "226",
	"flag" => "Equatorial-Guinea-Flag.png",
	),
	"GRC" => array(
	"iso" => "GR",
	"name" => "GREECE",
	"country" => "Greece",
	"numcode" => "300",
	"flag" => "Greece-Flag.png",
	),
	"GRD" => array(
	"iso" => "GD",
	"name" => "GRENADA",
	"country" => "Grenada",
	"numcode" => "308",
	"flag" => "Grenada-Flag.png",
	),
	"GRL" => array(
	"iso" => "GL",
	"name" => "GREENLAND",
	"country" => "Greenland",
	"numcode" => "304",
	"flag" => "Denmark-Flag.png",
	),
	"GS" => array(
	"iso" => "GS",
	"name" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
	"country" => "South Georgia and the South Sandwich Islands",
	"numcode" => "0",
	"flag" => "South-Korea-Flag.png",
	),
	"GTM" => array(
	"iso" => "GT",
	"name" => "GUATEMALA",
	"country" => "Guatemala",
	"numcode" => "320",
	"flag" => "Guatemala-Flag.png",
	),
	"GUF" => array(
	"iso" => "GF",
	"name" => "FRENCH GUIANA",
	"country" => "French Guiana",
	"numcode" => "254",
	"flag" => "France-Flag.png",
	),
	"GUM" => array(
	"iso" => "GU",
	"name" => "GUAM",
	"country" => "Guam",
	"numcode" => "316",
	"flag" => "Guam-Flag.png",
	),
	"GUY" => array(
	"iso" => "GY",
	"name" => "GUYANA",
	"country" => "Guyana",
	"numcode" => "328",
	"flag" => "Guyana-Flag.png",
	),
	"HKG" => array(
	"iso" => "HK",
	"name" => "HONG KONG",
	"country" => "Hong Kong",
	"numcode" => "344",
	"flag" => "Hong-Kong-Flag.png",
	),
	"HM" => array(
	"iso" => "HM",
	"name" => "HEARD ISLAND AND MCDONALD ISLANDS",
	"country" => "Heard Island and Mcdonald Islands",
	"numcode" => "0",
	"flag" => "Australia-Flag.png",
	),
	"HND" => array(
	"iso" => "HN",
	"name" => "HONDURAS",
	"country" => "Honduras",
	"numcode" => "340",
	"flag" => "Honduras-Flag.png",
	),
	"HRV" => array(
	"iso" => "HR",
	"name" => "CROATIA",
	"country" => "Croatia",
	"numcode" => "191",
	"flag" => "Croatia-Flag.png",
	),
	"HTI" => array(
	"iso" => "HT",
	"name" => "HAITI",
	"country" => "Haiti",
	"numcode" => "332",
	"flag" => "Haiti-Flag.png",
	),
	"HUN" => array(
	"iso" => "HU",
	"name" => "HUNGARY",
	"country" => "Hungary",
	"numcode" => "348",
	"flag" => "Hungary-Flag.png",
	),
	"IDN" => array(
	"iso" => "ID",
	"name" => "INDONESIA",
	"country" => "Indonesia",
	"numcode" => "360",
	"flag" => "Indonezia-Flag.png",
	),
	"IND" => array(
	"iso" => "IN",
	"name" => "INDIA",
	"country" => "India",
	"numcode" => "356",
	"flag" => "India-Flag.png",
	),
	"IRL" => array(
	"iso" => "IE",
	"name" => "IRELAND",
	"country" => "Ireland",
	"numcode" => "372",
	"flag" => "Ireland-Flag.png",
	),
	"IRN" => array(
	"iso" => "IR",
	"name" => "IRAN, ISLAMIC REPUBLIC OF",
	"country" => "Iran, Islamic Republic of",
	"numcode" => "364",
	"flag" => "Iran-Flag.png",
	),
	"IRQ" => array(
	"iso" => "IQ",
	"name" => "IRAQ",
	"country" => "Iraq",
	"numcode" => "368",
	"flag" => "Iraq-Flag.png",
	),
	"ISL" => array(
	"iso" => "IS",
	"name" => "ICELAND",
	"country" => "Iceland",
	"numcode" => "352",
	"flag" => "Iceland-Flag.png",
	),
	"ISR" => array(
	"iso" => "IL",
	"name" => "ISRAEL",
	"country" => "Israel",
	"numcode" => "376",
	"flag" => "Israel-Flag.png",
	),
	"ITA" => array(
	"iso" => "IT",
	"name" => "ITALY",
	"country" => "Italy",
	"numcode" => "380",
	"flag" => "Italy-Flag.png",
	),
	"JAM" => array(
	"iso" => "JM",
	"name" => "JAMAICA",
	"country" => "Jamaica",
	"numcode" => "388",
	"flag" => "Jamaica-Flag.png",
	),
	"JOR" => array(
	"iso" => "JO",
	"name" => "JORDAN",
	"country" => "Jordan",
	"numcode" => "400",
	"flag" => "Jordan-Flag.png",
	),
	"JPN" => array(
	"iso" => "JP",
	"name" => "JAPAN",
	"country" => "Japan",
	"numcode" => "392",
	"flag" => "Japan-Flag.png",
	),
	"KAZ" => array(
	"iso" => "KZ",
	"name" => "KAZAKHSTAN",
	"country" => "Kazakhstan",
	"numcode" => "398",
	"flag" => "Kazakhstan-Flag.png",
	),
	"KEN" => array(
	"iso" => "KE",
	"name" => "KENYA",
	"country" => "Kenya",
	"numcode" => "404",
	"flag" => "Kenya-Flag.png",
	),
	"KGZ" => array(
	"iso" => "KG",
	"name" => "KYRGYZSTAN",
	"country" => "Kyrgyzstan",
	"numcode" => "417",
	"flag" => "Kyrgyzstan-Flag.png",
	),
	"KHM" => array(
	"iso" => "KH",
	"name" => "CAMBODIA",
	"country" => "Cambodia",
	"numcode" => "116",
	"flag" => "Cambodia-Flag.png",
	),
	"KIR" => array(
	"iso" => "KI",
	"name" => "KIRIBATI",
	"country" => "Kiribati",
	"numcode" => "296",
	"flag" => "Kiribati-Flag.png",
	),
	"KNA" => array(
	"iso" => "KN",
	"name" => "SAINT KITTS AND NEVIS",
	"country" => "Saint Kitts and Nevis",
	"numcode" => "659",
	"flag" => "St-Kitts-and-Nevis-Flag.png",
	),
	"KOR" => array(
	"iso" => "KR",
	"name" => "KOREA, REPUBLIC OF",
	"country" => "Korea, Republic of",
	"numcode" => "410",
	"flag" => "South-Korea-Flag.png",
	),
	"KWT" => array(
	"iso" => "KW",
	"name" => "KUWAIT",
	"country" => "Kuwait",
	"numcode" => "414",
	"flag" => "Kuwait-Flag.png",
	),
	"LAO" => array(
	"iso" => "LA",
	"name" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
	"country" => "Lao People's Democratic Republic",
	"numcode" => "418",
	"flag" => "Laos-Flag.png",
	),
	"LBN" => array(
	"iso" => "LB",
	"name" => "LEBANON",
	"country" => "Lebanon",
	"numcode" => "422",
	"flag" => "Lebanon-Flag.png",
	),
	"LBR" => array(
	"iso" => "LR",
	"name" => "LIBERIA",
	"country" => "Liberia",
	"numcode" => "430",
	"flag" => "Liberia-Flag.png",
	),
	"LBY" => array(
	"iso" => "LY",
	"name" => "LIBYAN ARAB JAMAHIRIYA",
	"country" => "Libyan Arab Jamahiriya",
	"numcode" => "434",
	"flag" => "Libya-Flag.png",
	),
	"LCA" => array(
	"iso" => "LC",
	"name" => "SAINT LUCIA",
	"country" => "Saint Lucia",
	"numcode" => "662",
	"flag" => "Saint-Lucia-Flag.png",
	),
	"LIE" => array(
	"iso" => "LI",
	"name" => "LIECHTENSTEIN",
	"country" => "Liechtenstein",
	"numcode" => "438",
	"flag" => "Liechtenshein-Flag.png",
	),
	"LKA" => array(
	"iso" => "LK",
	"name" => "SRI LANKA",
	"country" => "Sri Lanka",
	"numcode" => "144",
	"flag" => "Sri-Lanka-Flag.png",
	),
	"LSO" => array(
	"iso" => "LS",
	"name" => "LESOTHO",
	"country" => "Lesotho",
	"numcode" => "426",
	"flag" => "Lesotho-Flag.png",
	),
	"LTU" => array(
	"iso" => "LT",
	"name" => "LITHUANIA",
	"country" => "Lithuania",
	"numcode" => "440",
	"flag" => "Lithuania-Flag.png",
	),
	"LUX" => array(
	"iso" => "LU",
	"name" => "LUXEMBOURG",
	"country" => "Luxembourg",
	"numcode" => "442",
	"flag" => "Luxembourg-Flag.png",
	),
	"LVA" => array(
	"iso" => "LV",
	"name" => "LATVIA",
	"country" => "Latvia",
	"numcode" => "428",
	"flag" => "Latvia-Flag.png",
	),
	"MAC" => array(
	"iso" => "MO",
	"name" => "MACAO",
	"country" => "Macao",
	"numcode" => "446",
	"flag" => "Macau-Flag.png",
	),
	"MAR" => array(
	"iso" => "MA",
	"name" => "MOROCCO",
	"country" => "Morocco",
	"numcode" => "504",
	"flag" => "Morocco-Flag.png",
	),
	"MCO" => array(
	"iso" => "MC",
	"name" => "MONACO",
	"country" => "Monaco",
	"numcode" => "492",
	"flag" => "Monaco-Flag.png",
	),
	"MDA" => array(
	"iso" => "MD",
	"name" => "MOLDOVA, REPUBLIC OF",
	"country" => "Moldova, Republic of",
	"numcode" => "498",
	"flag" => "Moldova-Flag.png",
	),
	"MDG" => array(
	"iso" => "MG",
	"name" => "MADAGASCAR",
	"country" => "Madagascar",
	"numcode" => "450",
	"flag" => "Madagascar-Flag.png",
	),
	"MDV" => array(
	"iso" => "MV",
	"name" => "MALDIVES",
	"country" => "Maldives",
	"numcode" => "462",
	"flag" => "Maldives-Flag.png",
	),
	"MEX" => array(
	"iso" => "MX",
	"name" => "MEXICO",
	"country" => "Mexico",
	"numcode" => "484",
	"flag" => "Mexico-Flag.png",
	),
	"MHL" => array(
	"iso" => "MH",
	"name" => "MARSHALL ISLANDS",
	"country" => "Marshall Islands",
	"numcode" => "584",
	"flag" => "Marshall-Islands-Flag.png",
	),
	"MKD" => array(
	"iso" => "MK",
	"name" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
	"country" => "Macedonia, the Former Yugoslav Republic of",
	"numcode" => "807",
	"flag" => "Macedonia-Flag.png",
	),
	"MLI" => array(
	"iso" => "ML",
	"name" => "MALI",
	"country" => "Mali",
	"numcode" => "466",
	"flag" => "Mali-Flag.png",
	),
	"MLT" => array(
	"iso" => "MT",
	"name" => "MALTA",
	"country" => "Malta",
	"numcode" => "470",
	"flag" => "Malta-Flag.png",
	),
	"MMR" => array(
	"iso" => "MM",
	"name" => "MYANMAR",
	"country" => "Myanmar",
	"numcode" => "104",
	"flag" => "Myanmar-Flag.png",
	),
	"MNG" => array(
	"iso" => "MN",
	"name" => "MONGOLIA",
	"country" => "Mongolia",
	"numcode" => "496",
	"flag" => "Mongolia-Flag.png",
	),
	"MNP" => array(
	"iso" => "MP",
	"name" => "NORTHERN MARIANA ISLANDS",
	"country" => "Northern Mariana Islands",
	"numcode" => "580",
	"flag" => "United-States-of-America-Flag.png",
	),
	"MOZ" => array(
	"iso" => "MZ",
	"name" => "MOZAMBIQUE",
	"country" => "Mozambique",
	"numcode" => "508",
	"flag" => "Mozambique-Flag.png",
	),
	"MRT" => array(
	"iso" => "MR",
	"name" => "MAURITANIA",
	"country" => "Mauritania",
	"numcode" => "478",
	"flag" => "Mauritania-Flag.png",
	),
	"MSR" => array(
	"iso" => "MS",
	"name" => "MONTSERRAT",
	"country" => "Montserrat",
	"numcode" => "500",
	"flag" => "Montserrat-Flag.png",
	),
	"MTQ" => array(
	"iso" => "MQ",
	"name" => "MARTINIQUE",
	"country" => "Martinique",
	"numcode" => "474",
	"flag" => "France-Flag.png",
	),
	"MUS" => array(
	"iso" => "MU",
	"name" => "MAURITIUS",
	"country" => "Mauritius",
	"numcode" => "480",
	"flag" => "Mauritius-Flag.png",
	),
	"MWI" => array(
	"iso" => "MW",
	"name" => "MALAWI",
	"country" => "Malawi",
	"numcode" => "454",
	"flag" => "Malawi-Flag.png",
	),
	"MYS" => array(
	"iso" => "MY",
	"name" => "MALAYSIA",
	"country" => "Malaysia",
	"numcode" => "458",
	"flag" => "Malaysia-Flag.png",
	),
	"NAM" => array(
	"iso" => "NA",
	"name" => "NAMIBIA",
	"country" => "Namibia",
	"numcode" => "516",
	"flag" => "Namibia-Flag.png",
	),
	"NCL" => array(
	"iso" => "NC",
	"name" => "NEW CALEDONIA",
	"country" => "New Caledonia",
	"numcode" => "540",
	"flag" => "France-Flag.png",
	),
	"NER" => array(
	"iso" => "NE",
	"name" => "NIGER",
	"country" => "Niger",
	"numcode" => "562",
	"flag" => "Niger-Flag.png",
	),
	"NFK" => array(
	"iso" => "NF",
	"name" => "NORFOLK ISLAND",
	"country" => "Norfolk Island",
	"numcode" => "574",
	"flag" => "Australia-Flag.png",
	),
	"NGA" => array(
	"iso" => "NG",
	"name" => "NIGERIA",
	"country" => "Nigeria",
	"numcode" => "566",
	"flag" => "Nigeria-Flag.png",
	),
	"NIC" => array(
	"iso" => "NI",
	"name" => "NICARAGUA",
	"country" => "Nicaragua",
	"numcode" => "558",
	"flag" => "Nicaragua-Flag.png",
	),
	"NIU" => array(
	"iso" => "NU",
	"name" => "NIUE",
	"country" => "Niue",
	"numcode" => "570",
	"flag" => "United-Kingdom-Flag.png",
	),
	"NLD" => array(
	"iso" => "NL",
	"name" => "NETHERLANDS",
	"country" => "Netherlands",
	"numcode" => "528",
	"flag" => "Netherlands-Flag.png",
	),
	"NOR" => array(
	"iso" => "NO",
	"name" => "NORWAY",
	"country" => "Norway",
	"numcode" => "578",
	"flag" => "Norway-Flag.png",
	),
	"NPL" => array(
	"iso" => "NP",
	"name" => "NEPAL",
	"country" => "Nepal",
	"numcode" => "524",
	"flag" => "Nepal-Flag.png",
	),
	"NRU" => array(
	"iso" => "NR",
	"name" => "NAURU",
	"country" => "Nauru",
	"numcode" => "520",
	"flag" => "Nauru-Flag.png",
	),
	"NZL" => array(
	"iso" => "NZ",
	"name" => "NEW ZEALAND",
	"country" => "New Zealand",
	"numcode" => "554",
	"flag" => "New-Zealand-Flag.png",
	),
	"OMN" => array(
	"iso" => "OM",
	"name" => "OMAN",
	"country" => "Oman",
	"numcode" => "512",
	"flag" => "Oman-Flag.png",
	),
	"PAK" => array(
	"iso" => "PK",
	"name" => "PAKISTAN",
	"country" => "Pakistan",
	"numcode" => "586",
	"flag" => "Pakistan-Flag.png",
	),
	"PAN" => array(
	"iso" => "PA",
	"name" => "PANAMA",
	"country" => "Panama",
	"numcode" => "591",
	"flag" => "Panama-Flag.png",
	),
	"PCN" => array(
	"iso" => "PN",
	"name" => "PITCAIRN",
	"country" => "Pitcairn",
	"numcode" => "612",
	"flag" => "United-Kingdom-Flag.png",
	),
	"PER" => array(
	"iso" => "PE",
	"name" => "PERU",
	"country" => "Peru",
	"numcode" => "604",
	"flag" => "Peru-Flag.png",
	),
	"PHL" => array(
	"iso" => "PH",
	"name" => "PHILIPPINES",
	"country" => "Philippines",
	"numcode" => "608",
	"flag" => "Philippines-Flag.png",
	),
	"PLW" => array(
	"iso" => "PW",
	"name" => "PALAU",
	"country" => "Palau",
	"numcode" => "585",
	"flag" => "Palau-Flag.png",
	),
	"PNG" => array(
	"iso" => "PG",
	"name" => "PAPUA NEW GUINEA",
	"country" => "Papua New Guinea",
	"numcode" => "598",
	"flag" => "Papua-New-Guinea-Flag.png",
	),
	"POL" => array(
	"iso" => "PL",
	"name" => "POLAND",
	"country" => "Poland",
	"numcode" => "616",
	"flag" => "Poland-Flag.png",
	),
	"PRI" => array(
	"iso" => "PR",
	"name" => "PUERTO RICO",
	"country" => "Puerto Rico",
	"numcode" => "630",
	"flag" => "Puerto-Rico-Flag.png",
	),
	"PRK" => array(
	"iso" => "KP",
	"name" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
	"country" => "Korea, Democratic People's Republic of",
	"numcode" => "408",
	"flag" => "North-Korea-Flag.png",
	),
	"PRT" => array(
	"iso" => "PT",
	"name" => "PORTUGAL",
	"country" => "Portugal",
	"numcode" => "620",
	"flag" => "Portugal-Flag.png",
	),
	"PRY" => array(
	"iso" => "PY",
	"name" => "PARAGUAY",
	"country" => "Paraguay",
	"numcode" => "600",
	"flag" => "Paraguay-Flag.png",
	),
	"PS" => array(
	"iso" => "PS",
	"name" => "PALESTINIAN TERRITORY, OCCUPIED",
	"country" => "Palestinian Territory, Occupied",
	"numcode" => "0",
	"flag" => "Palestine-Flag.png",
	),
	"PYF" => array(
	"iso" => "PF",
	"name" => "FRENCH POLYNESIA",
	"country" => "French Polynesia",
	"numcode" => "258",
	"flag" => "France-Flag.png",
	),
	"QAT" => array(
	"iso" => "QA",
	"name" => "QATAR",
	"country" => "Qatar",
	"numcode" => "634",
	"flag" => "Qatar-Flag.png",
	),
	"REU" => array(
	"iso" => "RE",
	"name" => "REUNION",
	"country" => "Reunion",
	"numcode" => "638",
	"flag" => "France-Flag.png",
	),
	"ROM" => array(
	"iso" => "RO",
	"name" => "ROMANIA",
	"country" => "Romania",
	"numcode" => "642",
	"flag" => "Romania-Flag.png",
	),
	"RUS" => array(
	"iso" => "RU",
	"name" => "RUSSIAN FEDERATION",
	"country" => "Russian Federation",
	"numcode" => "643",
	"flag" => "Russian-Federation-Flag.png",
	),
	"RWA" => array(
	"iso" => "RW",
	"name" => "RWANDA",
	"country" => "Rwanda",
	"numcode" => "646",
	"flag" => "Rwanda-Flag.png",
	),
	"SAU" => array(
	"iso" => "SA",
	"name" => "SAUDI ARABIA",
	"country" => "Saudi Arabia",
	"numcode" => "682",
	"flag" => "Saudi-Arabia-Flag.png",
	),
	"SDN" => array(
	"iso" => "SD",
	"name" => "SUDAN",
	"country" => "Sudan",
	"numcode" => "736",
	"flag" => "Sudan-Flag.png",
	),
	"SEN" => array(
	"iso" => "SN",
	"name" => "SENEGAL",
	"country" => "Senegal",
	"numcode" => "686",
	"flag" => "Senegal-Flag.png",
	),
	"SGP" => array(
	"iso" => "SG",
	"name" => "SINGAPORE",
	"country" => "Singapore",
	"numcode" => "702",
	"flag" => "Singapore-Flag.png",
	),
	"SHN" => array(
	"iso" => "SH",
	"name" => "SAINT HELENA",
	"country" => "Saint Helena",
	"numcode" => "654",
	"flag" => "United-Kingdom-Flag.png",
	),
	"SJM" => array(
	"iso" => "SJ",
	"name" => "SVALBARD AND JAN MAYEN",
	"country" => "Svalbard and Jan Mayen",
	"numcode" => "744",
	"flag" => "Norway-Flag.png",
	),
	"SLB" => array(
	"iso" => "SB",
	"name" => "SOLOMON ISLANDS",
	"country" => "Solomon Islands",
	"numcode" => "90",
	"flag" => "Solomon-Islands-Flag.png",
	),
	"SLE" => array(
	"iso" => "SL",
	"name" => "SIERRA LEONE",
	"country" => "Sierra Leone",
	"numcode" => "694",
	"flag" => "Sierra-Leone-Flag.png",
	),
	"SLV" => array(
	"iso" => "SV",
	"name" => "EL SALVADOR",
	"country" => "El Salvador",
	"numcode" => "222",
	"flag" => "El-Salvador-Flag.png",
	),
	"SMR" => array(
	"iso" => "SM",
	"name" => "SAN MARINO",
	"country" => "San Marino",
	"numcode" => "674",
	"flag" => "San-Marino-Flag.png",
	),
	"SOM" => array(
	"iso" => "SO",
	"name" => "SOMALIA",
	"country" => "Somalia",
	"numcode" => "706",
	"flag" => "Somalia-Flag.png",
	),
	"SPM" => array(
	"iso" => "PM",
	"name" => "SAINT PIERRE AND MIQUELON",
	"country" => "Saint Pierre and Miquelon",
	"numcode" => "666",
	"flag" => "France-Flag.png",
	),
	"STP" => array(
	"iso" => "ST",
	"name" => "SAO TOME AND PRINCIPE",
	"country" => "Sao Tome and Principe",
	"numcode" => "678",
	"flag" => "Sao-Tome-and-Principe-Flag.png",
	),
	"SUR" => array(
	"iso" => "SR",
	"name" => "SURINAME",
	"country" => "Suriname",
	"numcode" => "740",
	"flag" => "Suriname-Flag.png",
	),
	"SVK" => array(
	"iso" => "SK",
	"name" => "SLOVAKIA",
	"country" => "Slovakia",
	"numcode" => "703",
	"flag" => "Slovakia-Flag.png",
	),
	"SVN" => array(
	"iso" => "SI",
	"name" => "SLOVENIA",
	"country" => "Slovenia",
	"numcode" => "705",
	"flag" => "Slovenia-Flag.png",
	),
	"SWE" => array(
	"iso" => "SE",
	"name" => "SWEDEN",
	"country" => "Sweden",
	"numcode" => "752",
	"flag" => "Sweden-Flag.png",
	),
	"SWZ" => array(
	"iso" => "SZ",
	"name" => "SWAZILAND",
	"country" => "Swaziland",
	"numcode" => "748",
	"flag" => "Swaziland-Flag.png",
	),
	"SYC" => array(
	"iso" => "SC",
	"name" => "SEYCHELLES",
	"country" => "Seychelles",
	"numcode" => "690",
	"flag" => "Seychelles-Flag.png",
	),
	"SYR" => array(
	"iso" => "SY",
	"name" => "SYRIAN ARAB REPUBLIC",
	"country" => "Syrian Arab Republic",
	"numcode" => "760",
	"flag" => "Syria-Flag.png",
	),
	"TCA" => array(
	"iso" => "TC",
	"name" => "TURKS AND CAICOS ISLANDS",
	"country" => "Turks and Caicos Islands",
	"numcode" => "796",
	"flag" => "Turks-and-Caicos-Islands-Flag.png",
	),
	"TCD" => array(
	"iso" => "TD",
	"name" => "CHAD",
	"country" => "Chad",
	"numcode" => "148",
	"flag" => "Chad-Flag.png",
	),
	"TF" => array(
	"iso" => "TF",
	"name" => "FRENCH SOUTHERN TERRITORIES",
	"country" => "French Southern Territories",
	"numcode" => "0",
	"flag" => "France-Flag.png",
	),
	"TGO" => array(
	"iso" => "TG",
	"name" => "TOGO",
	"country" => "Togo",
	"numcode" => "768",
	"flag" => "Togo-Flag.png",
	),
	"THA" => array(
	"iso" => "TH",
	"name" => "THAILAND",
	"country" => "Thailand",
	"numcode" => "764",
	"flag" => "Thailand-Flag.png",
	),
	"TJK" => array(
	"iso" => "TJ",
	"name" => "TAJIKISTAN",
	"country" => "Tajikistan",
	"numcode" => "762",
	"flag" => "Tajikistan-Flag.png",
	),
	"TKL" => array(
	"iso" => "TK",
	"name" => "TOKELAU",
	"country" => "Tokelau",
	"numcode" => "772",
	"flag" => "New-Zealand-Flag.png",
	),
	"TKM" => array(
	"iso" => "TM",
	"name" => "TURKMENISTAN",
	"country" => "Turkmenistan",
	"numcode" => "795",
	"flag" => "Turkmenistan-Flag.png",
	),
	"TL" => array(
	"iso" => "TL",
	"name" => "TIMOR-LESTE",
	"country" => "Timor-Leste",
	"numcode" => "0",
	"flag" => "Timor-Leste-Flag.png",
	),
	"TON" => array(
	"iso" => "TO",
	"name" => "TONGA",
	"country" => "Tonga",
	"numcode" => "776",
	"flag" => "Tonga-Flag.png",
	),
	"TTO" => array(
	"iso" => "TT",
	"name" => "TRINIDAD AND TOBAGO",
	"country" => "Trinidad and Tobago",
	"numcode" => "780",
	"flag" => "Trinidad-and-Tobago-Flag.png",
	),
	"TUN" => array(
	"iso" => "TN",
	"name" => "TUNISIA",
	"country" => "Tunisia",
	"numcode" => "788",
	"flag" => "Tunisia-Flag.png",
	),
	"TUR" => array(
	"iso" => "TR",
	"name" => "TURKEY",
	"country" => "Turkey",
	"numcode" => "792",
	"flag" => "Turkey-Flag.png",
	),
	"TUV" => array(
	"iso" => "TV",
	"name" => "TUVALU",
	"country" => "Tuvalu",
	"numcode" => "798",
	"flag" => "Tuvalu-Flag.png",
	),
	"TWN" => array(
	"iso" => "TW",
	"name" => "TAIWAN, PROVINCE OF CHINA",
	"country" => "Taiwan, Province of China",
	"numcode" => "158",
	"flag" => "Taiwan-Flag.png",
	),
	"TZA" => array(
	"iso" => "TZ",
	"name" => "TANZANIA, UNITED REPUBLIC OF",
	"country" => "Tanzania, United Republic of",
	"numcode" => "834",
	"flag" => "Tanzania-Flag.png",
	),
	"UGA" => array(
	"iso" => "UG",
	"name" => "UGANDA",
	"country" => "Uganda",
	"numcode" => "800",
	"flag" => "Uganda-Flag.png",
	),
	"UKR" => array(
	"iso" => "UA",
	"name" => "UKRAINE",
	"country" => "Ukraine",
	"numcode" => "804",
	"flag" => "Ukraine-Flag.png",
	),
	"UM" => array(
	"iso" => "UM",
	"name" => "UNITED STATES MINOR OUTLYING ISLANDS",
	"country" => "United States Minor Outlying Islands",
	"numcode" => "0",
	"flag" => "United-States-of-America-Flag.png",
	),
	"URY" => array(
	"iso" => "UY",
	"name" => "URUGUAY",
	"country" => "Uruguay",
	"numcode" => "858",
	"flag" => "Uruguay-Flag.png",
	),
	"USA" => array(
	"iso" => "US",
	"name" => "UNITED STATES",
	"country" => "United States",
	"numcode" => "840",
	"flag" => "United-States-of-America-Flag.png",
	),
	"UZB" => array(
	"iso" => "UZ",
	"name" => "UZBEKISTAN",
	"country" => "Uzbekistan",
	"numcode" => "860",
	"flag" => "Uzbekistan-Flag.png",
	),
	"VAT" => array(
	"iso" => "VA",
	"name" => "HOLY SEE (VATICAN CITY STATE)",
	"country" => "Holy See (Vatican City State)",
	"numcode" => "336",
	"flag" => "Vatican-City-Flag.png",
	),
	"VCT" => array(
	"iso" => "VC",
	"name" => "SAINT VINCENT AND THE GRENADINES",
	"country" => "Saint Vincent and the Grenadines",
	"numcode" => "670",
	"flag" => "St-Vincent-and-the-Grenadines-Flag.png",
	),
	"VEN" => array(
	"iso" => "VE",
	"name" => "VENEZUELA",
	"country" => "Venezuela",
	"numcode" => "862",
	"flag" => "Venezuela-Flag.png",
	),
	"VGB" => array(
	"iso" => "VG",
	"name" => "VIRGIN ISLANDS, BRITISH",
	"country" => "Virgin Islands, British",
	"numcode" => "92",
	"flag" => "Virgin-Islands-British-Flag.png",
	),
	"VIR" => array(
	"iso" => "VI",
	"name" => "VIRGIN ISLANDS, U.S.",
	"country" => "Virgin Islands, U.s.",
	"numcode" => "850",
	"flag" => "Virgin-Islands-US-Flag.png",
	),
	"VNM" => array(
	"iso" => "VN",
	"name" => "VIET NAM",
	"country" => "Viet Nam",
	"numcode" => "704",
	"flag" => "Viet-Nam-Flag.png",
	),
	"VUT" => array(
	"iso" => "VU",
	"name" => "VANUATU",
	"country" => "Vanuatu",
	"numcode" => "548",
	"flag" => "Vanutau-Flag.png",
	),
	"WLF" => array(
	"iso" => "WF",
	"name" => "WALLIS AND FUTUNA",
	"country" => "Wallis and Futuna",
	"numcode" => "876",
	"flag" => "France-Flag.png",
	),
	"WSM" => array(
	"iso" => "WS",
	"name" => "SAMOA",
	"country" => "Samoa",
	"numcode" => "882",
	"flag" => "Samoa-Flag.png",
	),
	"YEM" => array(
	"iso" => "YE",
	"name" => "YEMEN",
	"country" => "Yemen",
	"numcode" => "887",
	"flag" => "Yemen-Flag.png",
	),
	"YT" => array(
	"iso" => "YT",
	"name" => "MAYOTTE",
	"country" => "Mayotte",
	"numcode" => "0",
	"flag" => "France-Flag.png",
	),
	"ZAF" => array(
	"iso" => "ZA",
	"name" => "SOUTH AFRICA",
	"country" => "South Africa",
	"numcode" => "710",
	"flag" => "South-Africa-Flag.png",
	),
	"ZMB" => array(
	"iso" => "ZM",
	"name" => "ZAMBIA",
	"country" => "Zambia",
	"numcode" => "894",
	"flag" => "Zambia-Flag.png",
	),
	"ZWE" => array(
	"iso" => "ZW",
	"name" => "ZIMBABWE",
	"country" => "Zimbabwe",
	"numcode" => "716",
	"flag" => "Zimbabwe-Flag.png",
	),
);